package com.example.palfinder.Person

enum class PossibleInterests ( val interest : Int) {
    GOLF(1),
    DISC_GOLF(2),
    FISHING(3),
    DANCING(4),
    MUSIC_COMPOSING(5),
    ART(6),
    PROGRAMMING(7),
    HUNTING(8),
    SPORTS(9),
    POLITICS(10),
    COOKING(11),
    FASHION_DESIGN(12),
    ARCHITECTURE(13),
    WHINE(14),
    READING(15),
    SAILING(16),
    CHESS(17),
    GO_GAME(18),
    ASTRONOMY(19),
    PHOTOGRAPHY(20),
    MOTORCYCLES(21),
    FAST_CARS(22),
    BIKES(23),
    UNUSUAL_LANGUAGES(24),
    SKATING(25),
    DIRT_BIKE(26),
    BOXING(27),
    MARTIAL_ARTS(28),
    MOVIE_MAKING(29),
    WILD_LIFE(30)
}